default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: novakj
  password: your_password
  
development:
  <<: *default
  database: techtools_development

test:
  <<: *default
  database: techtools_test

production:
  adapter: postgresql
  encoding: unicode
  database: techtools_production
  pool: 5
  username: novakj
  password: your_password
  host: localhost
